# Generated by Django 5.0.3 on 2024-03-04 11:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='django', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
